apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcosidekick.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "falcosidekick.name" . }}
    helm.sh/chart: {{ include "falcosidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.config.slack.webhookurl }}
  slack-webhookurl: "{{ .Values.config.slack.webhookurl | b64enc }}"
  {{- end }}
  {{- if .Values.config.teams.webhookurl }}
  teams-webhookurl: "{{ .Values.config.teams.webhookurl | b64enc }}"
  {{- end }}
  {{- if .Values.config.datadog.apikey }}
  datadog-apikey: "{{ .Values.config.datadog.apikey | b64enc }}"
  {{- end }}
  {{- if and .Values.config.influxdb.user .Values.config.influxdb.password }}
  influxdb-user: "{{ .Values.config.influxdb.user | b64enc }}"
  influxdb-password: "{{ .Values.config.influxdb.password | b64enc }}"
  {{- end }}
  {{- if and .Values.config.aws.accesskeyid .Values.config.aws.secretaccesskey }}
  aws-accesskeyid: "{{ .Values.config.aws.accesskeyid | b64enc }}"
  aws-secretaccesskey: "{{ .Values.config.aws.secretaccesskey | b64enc }}"
  {{- end }}
  {{- if and .Values.config.smtp.user .Values.config.smtp.password }}
  smtp-user: "{{ .Values.config.smtp.user | b64enc }}"
  smtp-password: "{{ .Values.config.smtp.password | b64enc }}"
  {{- end }}
  {{- if .Values.config.opsgenie.apikey }}
  opsgenie-apikey: "{{ .Values.config.opsgenie.apikey | b64enc }}"
  {{- end }}
