apiVersion: v1
appVersion: "2.14.0"
description: A simple daemon to help you with falco's outputs
icon: https://raw.githubusercontent.com/falcosecurity/falcosidekick/master/imgs/falcosidekick.png
name: falcosidekick
version: 0.1.21
maintainers:
  - name: Issif
